import { ArticlePage, H1, H2, P, UL, LI, DocImage, Callout, PageLink } from "../ArticlePage";
import type { KBPage } from "../KnowledgeBase";

const TOC = [
  { id: "overview",             label: "Overview" },
  { id: "panel-layout",         label: "Alerts vs Notifications",       level: 2 as const },
  { id: "provisioning",         label: "Order & Provisioning Updates",  level: 2 as const },
  { id: "performance-alerts",   label: "VISTA Performance Alerts",     level: 2 as const },
  { id: "managing",             label: "Managing the Feed",             level: 2 as const },
];

interface Props {
  onNavigate: (page: KBPage) => void;
}

export function NotificationsPage({ onNavigate }: Props) {
  return (
    <ArticlePage toc={TOC}>
      <H1 id="overview">Alerts &amp; Notifications</H1>
      <div style={{ display: "flex", alignItems: "center", gap: 8, margin: "8px 0 20px" }}>
        <ReadTime minutes={4} />
        <Dot />
        <Tag label="Getting Around" color="#1c808d" />
      </div>

      <P>
        The bell icon in the top navigation opens the <strong>Alerts &amp; Notifications</strong> slide-over
        drawer — your central activity hub tracking both real-time network telemetry alarms and account lifecycle
        milestones. A red badge on the bell highlights whenever new unread items require your attention.
      </P>

      {/* ── Panel Layout ── */}
      <H2 id="panel-layout">Alerts vs Notifications</H2>
      <P>
        The drawer separates platform events into two dedicated tabs so operational alarms never get buried under
        routine account activity:
      </P>
      <UL>
        <LI>
          <strong>Alerts</strong> — telemetry-driven warnings and threshold breaches generated by VISTA, such as
          sudden availability drops, bandwidth saturation, or latency spikes.
        </LI>
        <LI>
          <strong>Notifications</strong> — service provisioning updates, order confirmations, subscription renewals,
          and lifecycle transitions across all your connections and ports.
        </LI>
      </UL>
      <DocImage
        src="/screenshots/notifications/01-notifications-tab.jpg"
        alt="Alerts & Notifications drawer showing the Notifications tab"
        caption="① Tab switcher (Alerts vs Notifications) — ② Filter by All / Unread and Mark All as Read — ③ Service provisioning and order lifecycle updates"
      />

      {/* ── Order & Provisioning Updates ── */}
      <H2 id="provisioning">Order &amp; Provisioning Updates</H2>
      <P>
        Selecting the <strong>Notifications</strong> tab <strong>①</strong> displays a chronological log of your
        services moving through each stage of deployment. Each notification card <strong>③</strong> identifies the
        affected resource and its new state:
      </P>
      <UL>
        <LI>
          <strong>Saved in Design State</strong> — the service configuration is drafted and stored, awaiting your
          final review and order submission.
        </LI>
        <LI>
          <strong>Ready to Patch state</strong> — your port or connection has been deployed in the physical network
          and is ready for cross-connect or patch cabling.
        </LI>
        <LI>
          <strong>Subscription created successfully</strong> — confirms an active billing subscription has been
          provisioned and linked to your service.
        </LI>
      </UL>
      <P>
        To learn what each lifecycle milestone means and how orders progress, see{" "}
        <PageLink label="Understanding Service Status" onClick={() => onNavigate("service-status")} />.
      </P>

      {/* ── VISTA Performance Alerts ── */}
      <H2 id="performance-alerts">VISTA Performance Alerts</H2>
      <P>
        Switching to the <strong>Alerts</strong> tab reveals active operational alerts triggered when monitored
        telemetry crosses your configured thresholds in VISTA:
      </P>
      <UL>
        <LI>
          <strong>Severity Badges ①</strong> — flags each issue as <strong>Critical</strong> (red diamond) or{" "}
          <strong>Info</strong> (blue circle), along with the exact time raised and ongoing duration (e.g.{" "}
          <em>7m ongoing</em>).
        </LI>
        <LI>
          <strong>Threshold Details ②</strong> — provides a plain-language summary of what happened (e.g. availability
          dropping below your 95% or 100% alert level) and clearly states the <strong>Affected Service</strong> ID.
        </LI>
        <LI>
          <strong>Direct Action Shortcuts ③</strong> — provides one-click shortcuts right on the alert card:{" "}
          <strong>View alert →</strong> jumps to the rule definition under Settings &gt; Manage Alerts, while{" "}
          <strong>Check performance →</strong> opens the live telemetry dashboards in VISTA for that specific service.
        </LI>
      </UL>
      <DocImage
        src="/screenshots/notifications/02-alerts-tab.jpg"
        alt="Alerts tab displaying VISTA performance alerts and action shortcuts"
        caption="① Severity badges (Critical / Info) and duration — ② Telemetry threshold breach and affected Service ID — ③ Direct shortcuts to View alert and Check performance"
      />
      <Callout variant="tip">
        Clicking <strong>Check performance →</strong> directly opens the real-time VISTA graphs for that affected
        connection, saving you from having to search for the service manually. See{" "}
        <PageLink label="VISTA" onClick={() => onNavigate("vista-overview")} /> for configuring metrics and thresholds.
      </Callout>

      {/* ── Managing ── */}
      <H2 id="managing">Managing the Feed</H2>
      <P>
        Both the Alerts and Notifications tabs include identical management controls at the top <strong>②</strong>:
      </P>
      <UL>
        <LI>
          <strong>All vs. Unread</strong> — toggle to <strong>Unread</strong> to isolate only items you haven't
          acknowledged yet, keeping your focus on immediate actions.
        </LI>
        <LI>
          <strong>Mark All as Read</strong> — clears the unread badge and counter without having to open each item
          individually.
        </LI>
        <LI>
          <strong>Historical Feed</strong> — read notifications stay grouped by day (e.g. <em>Today</em>,{" "}
          <em>Yesterday</em>) even after acknowledgement, allowing you to easily scroll back through recent changes.
        </LI>
        <LI>
          <strong>Dismiss Drawer</strong> — click the close icon (<strong>✕</strong>) in the top-right corner or click
          anywhere outside the drawer to return to your current screen.
        </LI>
      </UL>
    </ArticlePage>
  );
}

function ReadTime({ minutes }: { minutes: number }) {
  return <span style={{ fontFamily: "'Lato', sans-serif", fontSize: 12, color: "#94a3b8" }}>{minutes} min read</span>;
}
function Dot() {
  return <span style={{ width: 3, height: 3, borderRadius: "50%", background: "#cbd5e1", display: "inline-block" }} />;
}
function Tag({ label, color }: { label: string; color: string }) {
  return <span style={{ fontFamily: "'Lato', sans-serif", fontSize: 12, fontWeight: 700, color, background: `${color}18`, border: `1px solid ${color}33`, padding: "2px 10px", borderRadius: 20 }}>{label}</span>;
}
